package ch.giime.fensterquiz


class QuestlionList() {
    fun ListGenerator() : ArrayList<Questions>{
        val QuestionList = ArrayList<Questions>()
        QuestionList.add(Questions("Wieviele Sicherheitsstufen gibt es für ein Fenster?", "Es gibt drei Sicherheitsstufen.\n", "Es gibt zwei Sicherheitsstufen.\n", "Es gibt fünf Sicherheitsstufen.\n", 1, "Es gibt drei Sicherheitsstufen.\nAS-1 Grundsicherheit\n" +
                "AS-2 erhöhte Anzahl von Schliesspunkten und somit einen stark verbesserten Einbruchschutz.\n" +
                "AS-3 Ein Maximum an Verschlusspunkten verhindern ein Eindringen auch mit schwerem Einbruchswerkzeug."))
        QuestionList.add(Questions("Wann wurde die Firma Alpsteg Fenster AG gegründet?", "1853\n", "1978\n", "1964\n", 2, "Die Alpsteg Fenster AG ist im Jahre 1978 aus der Schreinerei Alpsteg in Dürrenäsch im Kanton Aargau hervorgegangen. Als einer der Pioniere der Branche wurde vor mehr als 40 Jahren mit der Fertigung von Kunststoff-Fenster begonnen."))
        QuestionList.add(Questions("Wie stark haben sich die Werte der Isolierung der Fenster von 1970 zu heute verbessert?", "3x bessere Werte\n", "ganze 8x bessere Werte\n", "6x bessere Werte\n", 3, "Die Verbesserung des \"W/m2-Wertes\" konnte nicht nur halbiert werden sondern die Optimierung heute zum Jahre 1970 ist knappe 6x besser. Neue Fenster machen eine bessere Isolation und somit tiefere Heizkosten möglich.\n1970  -  Verglasung üblich 1-Fach  -  ergibt einen U-Wert von ca. 5.0W/m2\n2020  -  Verglasung üblich 3-Fach  -  ergibt einen U-Wert von ca. 0.85W/m2"))
        QuestionList.add(Questions("Das Fensterglas ist auf der Aussenseite beschlagen. Ein Zeichen für?", "Das Fenster isoliert sehr gut.\n", "Das Glas ist altershalber nicht mehr dicht. Das Fenster muss ersetzt werden.\n", "Wieder mal querlüften für einen gründlichen Luftaustausch.\n", 1,"Das Fenster isoliert sehr gut. Dies bedeutet, dass das Glas so gut isoliert, dass die äussere Scheibe so kalt ist, dass sich Kondenswasser bilden kann. Die Isolierung dieses Glases ist somit so gut, dass die Wärme des Innenraumes nicht mal an die äusserste Scheibe gelangt. Dies taucht vor allem in den Morgenstunden der Übergangsmonaten auf. Sobald sich die Aussentemperatur wieder verändert, verschwindet dies wieder."))
        QuestionList.add(Questions("Wie kann man einfach prüfen, ob mein Fenster dreifach verglast ist?", "Den Glassteg entfernen und in den Glasfalz schielen.\n", "Mit einem Feuerzeug\n", "Das Glas von aussen gegen das Licht genau betrachten.\n", 2, "Mit der Flamme eines Feuerzeugs an die Scheibe ran. So oft sich die Flamme spiegelt, soviel Scheiben sind im Fenster verbaut. Aber bitte Vorsicht beim Spiel mit dem Feuer. ;-)"))
        QuestionList.add(Questions("Wie viel Glasscheiben hat ein heutiges Standard-Fenster?", "2 Scheiben. Somit eine 2-fach Verglasung\n", "Im Standard ist es nur eine Scheibe.\n", "3 Scheiben. Somit eine 3-fach Verglasung\n", 3, "Es sind drei Scheiben. Dieses Glaspaket ist das sogenannte \"Isolierglas\". \n" +
                "Der Zwischenraum ist mit Gas gefüllt. Dies bewirkt, dass der heutige Standard an Wärmeisolierung gewährleistet werden kann.\n" +
                "Der Randverbund welcher den Abstand vom Zwischenraum aufrecht erhält und diesen hermetisch abriegelt ist entscheidend damit keine Luft in den Zwischenraum gelangen kann und kein Gas entweichen kann. Falls Luft in den Zwischenraum gelangen würde, hätte man das Risiko von \"blinden Gläser\". Die Scheiben könnten anlaufen oder es könnte sich Kondenswasser bilden, da die eintretende Luft Feuchtigkeit mitbringt. Ein intakter Randverbund ist entscheidend für eine gute Durchsicht."))
        QuestionList.add(Questions("Was ist zu beachten bei einem Vollrahmenersatz?", "Die Fenster zugänglich machen. Faustregel 1.5m um das Fenster\n", "Die alten Fenster vor der Demontage sauber reinigen.\n", "Maurer aufbieten, da die Mauer aufgespitzt werden muss.\n", 1, "Die Fenster zurgänglich machen.\nBei einem Vollrahmenersatz wird das bestehende Fenster so schonend wie nur möglich rausgeschnitten und der neue Rahmen wird in die Leibung gesetzt. So ist nach der Sanierung nicht bis kaum zu erkennen, dass in dieser Leibung ein neues Fenster angeschlagen ist. \n" +
                "Ausser die Vorteile des neuen Fensters und des Wohngefühls natürlich. ;-) "))
        QuestionList.add(Questions("Welche Fenster stellt die Alpsteg Fenster AG selbst her?","Holz- und Holz-Metallfenster\n", "Kunststofffenster\n","Aluminiumfenster\n", 1 ,"Die Firma Alpsteg Fenster AG produziert Holz und Holz-Metallfenster in Niederlenz."))
        QuestionList.add(Questions("Welches sind die Partnerfirmen der Alpsteg Fenster AG und gehören somit in die selbe Gruppe?","sirius, Koch AG und SFS unimarket AG\n","Roto Frank, Traitafina AG und Eschbal AG\n","Balteschwiler AG, SAICOS COLOUR GmbH und Corabois SA\n",3,"Balteschwiler AG, SAICOS COLOUR GmbH und Corabois SA gehören in die selbe Gruppe. \nDie Cura Beteiligungen AG"))
        QuestionList.add(Questions("Ab welcher Einbauhöhe (ab Boden bis zum Glaslicht) muss ein Sicherheitsglas eingebaut werden?","über 1'000mm\n","unter 1'000mm\n","Nur bei erhöhtem Einbruchschutz. Da ist die Höhe jedoch irrelevant\n",2,"Gemäss der SIGAB002 muss jedes Glas welches unter 1'000mm fällt ein Sicherheitsglas sein."))
        QuestionList.add(Questions("Was für Produkte bietet die Alpsteg Fenster AG an?","Fenster und Garagentore\n", "Fenster, Hauseingangstüren und Briefkästen\n", "Fenster, Hauseingangstüren und Beschattungen\n",3,"Fenster, Hauseingangstüren und Beschattungen darin ist die Firma Alpsteg Fenster AG stark. Überzeugen Sie sich!"))
        QuestionList.add(Questions("Wo befindet sich die Produktion von Alpsteg Fenster AG?","Niederlenz\n","Rokycany (Ort in Tschechien)\n", "Lenzburg\n",1,"Die Firma Alpsteg Fenster AG produziert in der Schweiz! Der Standort des Werkes ist Niederlenz"))
        QuestionList.add(Questions("Was dürfen Sie von der Firma Alpsteg Fenster AG erwarten?","Beratung, Produktion und Montage\n", "Beratung und Produktion\n","Produktion und Montage\n",1,"Beratungen bei Ihnen vor Ort sind selbstverständlich, produziert wird in der Schweiz und eine saubere Montage gehört dazu! Ein kompetenter Kundendienst für die Pflege und Ersatzteile ist natürlich auch vorhanden. Die Alpsteg Fenster AG lässt Sie auch nach der Montage nicht im Stich!"))
        QuestionList.add(Questions("Die Kunden von Alpsteg Fenster AG sind:","Privatkunden und Architekten\n","Wiederverkäufer\n","Privatkunden, Architekten und Wiederverkäufer\n",3,"Alpsteg Fenster AG zählt Privatkunden, Architekten wie auch Wiederverkäufer zu ihren Kunden."))
        return QuestionList
    }

}
